/*

 HIROMU.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char hiromu[] =
{
  0x3E,0x3E,0x7E,0x7E,0x7E,0x62,0xFC,0xE0,
  0xF0,0xEC,0x20,0x1C,0x48,0x14,0xFF,0xFB
};

/* End of HIROMU.C */
